# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
#https://www.freepik.com/free-vector/v60-pla-kala-26c-animals_3129755.htm#page=1&query=golden%20retriever&position=2
#title:		           "Lambda"
title:               <img src="https://github.com/vcobop/lambda_blog/blob/gh-pages/assets/img/lambda-logo.jpg" alt="Lambda logo">
description:	       "personal blog focused in bioinformatic topics"
author:              "Valentina Cobo"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
